title: cd-sebento-scratch-2
hero_image: images/banner.png
description: cd-sebento-scratch-2 description
version: 4
listed: false
copyedit: false
last_tested: "2018-04-12"
steps:
  - title: Introduction
  - title: What you will need
  - title: Calculate water usage
  - title: Draw a chart
  - title: Using a list
  - title: Matching things up
  - title: Repetition is key
  - title: Final tweaks
