title: Intermediate Scratch Sushi Cards
hero_image: images/banner.png
description: Make a water usage calculator and animated charts to illustrate water usage for various activities.
version: 1
listed: false
copyedit: false
last_tested: "2018-04-12"
steps:
  - title: Introduction
  - title: What you will need
  - title: Getting information from the user
  - title: Draw a chart
  - title: Using a list
  - title: Matching things up
  - title: Repetition is key
  - title: Final tweaks
